---
- hosts: all
  pre_tasks:
    - name: System details
      debug: msg="{{ item }}"
      with_items: 
      - "{{ ansible_distribution }}"
      - "{{ ansible_distribution_release }}"
      - "{{ ansible_distribution_version }}"
      - "{{ ansible_distribution_major_version }}"
    - name: update repositories
      become: true
      apt: update_cache=yes
      changed_when: false
  tasks:
    - include_tasks: tasks/touchegg.yml
  post_tasks:
    - name: Remove useless packages from the cache
      become: true
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      become: true
      apt:
        autoremove: yes
