---
- hosts: localhost
  pre_tasks:
    - name: update repositories
      become: yes
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/main-packages.yml
    - include: tasks/gnome-packages.yml
    - include: tasks/kde-packages.yml
    - include: tasks/java-packages.yml
    - include: tasks/google-chrome.yml
    - include: tasks/dropbox.yml
    - include: tasks/docker.yml
  post_tasks:
    - name: Remove useless packages from the cache
      become: yes
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      become: yes
      apt:
        autoremove: yes
      register: aptout

    - debug: msg="{{ aptout.stdout_lines }}"
      when: aptout.stdout_lines is defined

