---
- hosts: all
  pre_tasks:
    - name: System details
      debug: msg="{{ item }}"
      with_items: 
      - "{{ ansible_distribution }}"
      - "{{ ansible_distribution_release }}"
      - "{{ ansible_distribution_version }}"
      - "{{ ansible_distribution_major_version }}"
    - name: update repositories
      become: true
      apt: update_cache=yes
      changed_when: False
  tasks:
    - block:
      - include_tasks: tasks/git.yml
      tags: git
    - name: Install GNOME
      ansible.builtin.include_role:
        name: lorenzobettini.my_gnome_role
      vars:
        modify_dconf: false
    - include_tasks: tasks/main-packages.yml
    - include_tasks: tasks/homebrew.yml
    - include_tasks: tasks/firefox.yml
    - name: Install Oh My Zsh
      ansible.builtin.include_role:
        name: lorenzobettini.oh_my_zsh
      vars:
        with_starship: false
        copy_dot_files: false
    # Kvantum is needed to theme Kate in Gnome correctly
    - include_tasks: tasks/zsh-gnome.yml
    - include_tasks: tasks/kvantum.yml
    - include_tasks: tasks/kde-gnome-packages.yml
    - include_tasks: tasks/java-packages.yml
    - include_tasks: tasks/google-chrome.yml
    - include_tasks: tasks/dropbox.yml
    - block:
      - include_tasks: tasks/docker.yml
      tags: docker
    - include_tasks: tasks/recoll.yml
    - include_tasks: tasks/vscode.yml
    - include_tasks: tasks/ubuntu-restricted-extras.yml
    - include_tasks: tasks/other-packages.yml
    - include_tasks: tasks/version-dependent-packages.yml
    - include_tasks: tasks/touchegg.yml
      when: ansible_distribution_version is version('20.04', '>=') and ansible_distribution_version is version('22.04', '<')
      # In 22.04 I use Wayland where touchpad gestures work automatically
    # Skype requires snap and does not work well in Ansible/Docker/Systemd
    #- include_tasks: tasks/skype.yml
    - include_tasks: tasks/amarok.yml # Amarok not yet available in Jammy
      when: ansible_distribution_version is version('22.04', '<')
    - include_tasks: tasks/kernel-mainline.yml
    - block:
      - include_tasks: tasks/latex.yml
      tags: latex
  post_tasks:
    - name: Dist-upgrade
      become: true
      apt:
        upgrade: dist

    - name: Remove useless packages from the cache
      become: true
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      become: true
      apt:
        autoremove: yes
