---
- hosts: localhost
  tasks:

  - name: Install Main Packages
    become: yes
    apt:
      update_cache: yes
      state: latest
      pkg:
      - vim
      - curl
      - wget
      - curl
      - git
      - git-gui
      - gitk
      - apt-transport-https
      - unison-gtk
      - thunderbird
    register: aptout

  - debug: msg="{{ aptout.stdout_lines }}"
    when: aptout.stdout_lines is defined

  - name: Install Gnome Packages
    become: yes
    apt:
      update_cache: yes
      state: latest
      pkg:
      - gnome-tweaks
      - dconf-editor
    register: aptout

  - debug: msg="{{ aptout.stdout_lines }}"
    when: aptout.stdout_lines is defined

  - name: Add Google Chrome apt key
    become: yes
    apt_key:
      url: https://dl-ssl.google.com/linux/linux_signing_key.pub
      state: present

  - name: Add Google Chrome apt repository
    become: yes
    apt_repository:
      repo: deb https://dl.google.com/linux/chrome/deb/ stable main
      state: present

  - name: Install Google Chrome
    become: yes
    apt:
      update_cache: yes
      state: latest
      pkg:
      - google-chrome-stable
    register: aptout

  - debug: msg="{{ aptout.stdout_lines }}"
    when: aptout.stdout_lines is defined

  - name: Install Docker
    become: yes
    apt:
      update_cache: yes
      state: latest
      pkg:
      - docker.io
      - docker-compose
    register: aptout

  - debug: msg="{{ aptout.stdout_lines }}"
    when: aptout.stdout_lines is defined

  - name: Allow running Docker without sudo
    become: yes
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes

  - name: Remove useless packages from the cache
    become: yes
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    become: yes
    apt:
      autoremove: yes
    register: aptout

  - debug: msg="{{ aptout.stdout_lines }}"
    when: aptout.stdout_lines is defined

