---
- hosts: localhost
  become: yes
  tasks:
  - name: Update all packages for Debian-like Systems
    apt:
      update_cache: yes
      name: '*'
      force_apt_get: yes
      state: latest
    when: ansible_facts['os_family'] == 'Debian'
  - name: Install Main Packages
    package:
      name: "{{packages}}"
      state: present
    vars:
      packages:
        - vim
        - curl
        - wget
        - curl
        - git
        - git-gui
        - gitk
        - apt-transport-https
        - unison-gtk
        - thunderbird
