---
roles:
  # Install a role from Ansible Galaxy.
  - name: gantsign.maven
  # Install my own roles from GitHub
  - name: lorenzobettini.oh_my_zsh
    src: https://github.com/LorenzoBettini/ansible-molecule-oh-my-zsh-example/
  - name: lorenzobettini.my_gnome_role
    src: https://github.com/LorenzoBettini/my_gnome_role/
  - name: lorenzobettini.my_kde_role
    src: https://github.com/LorenzoBettini/my_kde_role/
  # transitive dependencies
  # required by my_gnome_role
  - name: petermosmans.customize-gnome
    version: 0.2.10

collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
    version: 6.4.0
    # pin older version until https://github.com/ansible-collections/community.general/issues/6271 is fixed
