---
- name: Add Amarok KF5 snapshots with Codename
  become: true
  apt_repository:
    repo: ppa:pgomes/amarok
    state: present
    codename: hirsute # Impish not yet supported
  when: ansible_distribution_version is version('21.10', '>=')

- name: Add Amarok KF5 snapshots with automatic Codename
  become: true
  apt_repository:
    repo: ppa:pgomes/amarok
    state: present
  when: ansible_distribution_version is version('21.10', '<')

- name: Install Amarok
  become: true
  apt:
    update_cache: yes
    state: latest
    pkg:
    - amarok
    - breeze-icon-theme
  register: aptout

- debug: msg="{{ aptout.stdout_lines }}"
  when: aptout.stdout_lines is defined
