---
- name: Remove possible Docker install from docker.com
  # if installed from https://docs.docker.com/engine/install/ubuntu/
  become: true
  apt:
    state: absent
    pkg:
    - docker-ce

- name: Remove possible docker-compose installed from github
  # if installed from https://github.com/docker/compose/releases/download/
  become: true
  file:
    path: '/usr/local/bin/docker-compose'
    state: absent

- name: Install Docker from Ubuntu APT
  become: true
  apt:
    state: present
    pkg:
    - runc
    - containerd
    - docker.io
    - docker-compose

- name: Allow running Docker without sudo
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

# Then, you have to explicitly start docker.service
# systemctl start docker.service.
# With service module, when running in Docker in molecule
# we get this error FAILED! =>
# "msg": "Could not find the requested service docker: host"
# with systemd module instead it works
- name: Do NOT enable service docker on boot
  become: yes
  ansible.builtin.systemd:
    name: docker.service
    enabled: no

# This way, as soon as we run a docker command docker.service starts
- name: Enable docker.socket on boot
  become: yes
  ansible.builtin.systemd:
    name: docker.socket
    enabled: yes
