---
- name: Copy Dropbox apt key
  # The apt_key file is expected to be found on the remote host
  # so we first need to copy it
  become: true
  copy:
    src: "{{ playbook_dir }}/tasks/files/keys/dropbox.asc"
    dest: "/tmp/"
    mode: 0600

# To update the local PGP key:
# - download the latest dropbox dep package
# - open it as an archive file
# - open as an archive file the control.tar.zst
# - open the postinst script
# - take the PGP key from there

- name: Add Dropbox key
  become: true
  apt_key:
    file: "/tmp/dropbox.asc"
    state: present

# Let's use the Disco repository for good
- name: Add Dropbox apt repository
  become: true
  apt_repository:
    repo: "deb [arch=i386,amd64 signed-by=/etc/apt/keyrings/dropbox.asc] http://linux.dropbox.com/ubuntu noble main"
    state: present
    filename: dropbox

- name: Install Dropbox
  become: true
  apt:
    name: dropbox
    update_cache: yes
    state: present
  register: result
  retries: 5
  delay: 10
  until: result is not failed
# downloading from https://linux.dropbox.com/
# is extremely flaky, but ignoring errors might undermine idempotency