---
- name: Copy Dropbox apt key
  # The apt_key file is expected to be found on the remote host
  # so we first need to copy it
  become: true
  copy:
    src: "{{ playbook_dir }}/tasks/files/keys/dropbox.gpg"
    dest: "/tmp/"
    mode: 0600

- name: Add Dropbox key
  become: true
  apt_key:
    # use locally save key to avoid possible temporary failures
    # keyserver: pgp.mit.edu
    # id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
    file: "/tmp/dropbox.gpg"
    state: present

# Let's use the Disco repository for good
- name: Add Dropbox apt repository
  become: true
  apt_repository:
    repo: "deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu noble main"
    state: present
    filename: dropbox

- name: Install Dropbox
  become: true
  apt:
    name: dropbox
    update_cache: yes
    state: present
  register: result
  retries: 5
  delay: 10
  until: result is not failed
# downloading from https://linux.dropbox.com/
# is extremely flaky, but ignoring errors might undermine idempotency