- name: Install Dropbox key
  become: yes
  apt_key:
    keyserver: pgp.mit.edu
    id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E

- name: Add Dropbox apt repository
  become: yes
  apt_repository:
    repo: deb https://linux.dropbox.com/ubuntu disco main
    state: present

- name: Install Dropbox
  become: yes
  apt:
    name: dropbox
    state: present
  register: aptout

- debug: msg="{{ aptout.stdout_lines }}"
  when: aptout.stdout_lines is defined
