---
- name: Remove Firefox Snap
  become: yes
  snap:
    state: absent
    name: firefox

- name: Install Firefox from APT
  become: yes
  apt:
    state: latest
    pkg: firefox
  register: aptout

- debug: msg="{{ aptout.stdout_lines }}"
  when: aptout.stdout_lines is defined