---
- name: Install Git Packages
  become: true
  apt:
    state: present
    pkg:
    - git
    - git-gui
    - gitk
  register: aptout

- debug: msg="{{ aptout.stdout_lines }}"
  when: aptout.stdout_lines is defined
