---
- name: Add Google APT repository
  ansible.builtin.deb822_repository:
    name: google-chrome
    types: [deb]
    uris:
      - "http://dl.google.com/linux/chrome/deb"
    signed_by: "https://dl.google.com/linux/linux_signing_key.pub"
    suites: [stable]
    components: [main]
    state: present
    enabled: yes

- name: Install Google Chrome
  ansible.builtin.apt:
    update_cache: true
    name: google-chrome-stable
    state: present

# During the installation, Google Chrome creates the google-chrome.list file
# which is redundant and generates during "apt update" the warning:
# Target Packages (main/binary-amd64/Packages) is configured multiple times
# in /etc/apt/sources.list.d/google-chrome.list:3 and /etc/apt/sources.list.d/google-chrome.sources:1
- name: Remove /etc/apt/sources.list.d/google-chrome.list
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/google-chrome.list
    state: absent