- name: Add Google Chrome apt key
  become: yes
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

# This way we avoid Chrome setting up the APT repository:
# we want to set up it ourselves
- name: Touch /etc/default/google-chrome
  become: yes
  file:
    path: /etc/default/google-chrome
    state: touch

- name: Add Google Chrome apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Install Google Chrome
  become: yes
  apt:
    update_cache: yes
    state: latest
    pkg:
    - google-chrome-stable
  register: aptout

- debug: msg="{{ aptout.stdout_lines }}"
  when: aptout.stdout_lines is defined
