- name: Install Guake Drop-down Terminal
  become: yes
  apt:
    state: latest
    pkg:
    - guake
  register: aptout

- debug: msg="{{ aptout.stdout_lines }}"
  when: aptout.stdout_lines is defined
