---
- name: Install Guake Drop-down Terminal
  become: true
  apt:
    state: present
    pkg:
    - guake
  register: aptout

- debug: msg="{{ aptout.stdout_lines }}"
  when: aptout.stdout_lines is defined
