---
# REQUIRED: git curl
# must NOT be installed with sudo
- name: Install Homebrew
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew

- name: Install brew packages
  community.general.homebrew:
    name:
    - chezmoi
    - neovim # the version in Ubuntu repos is too old for lazy.vim
    - shellcheck
    - lazygit
    state: present

- name: Install Neovim requirements
  become: true
  ansible.builtin.package:
    name:
    - npm # required for some neovim LSPs, e.g., bashls
    - wl-clipboard # for neovim clipboard sharing in Wayland
    - xclip # for neovim clipboard sharing in X11
    - tree-sitter-cli # for latex tree-sitter
    - git-delta # for better git diffs in Lazygit
    state: present
