---
- name: Install Kde Packages
  become: true
  apt:
    state: latest
    pkg:
    - latte-dock
    - yakuake
    - korganizer
    - kaddressbook
    - ksshaskpass
    - kdepim-addons
    - kio-gdrive
    - dolphin-plugins
  register: aptout

- debug: msg="{{ aptout.stdout_lines }}"
  when: aptout.stdout_lines is defined
