---
- name: Copy Mainline apt key
  # The apt_key file is expected to be found on the remote host
  # so we first need to copy it
  become: true
  copy:
    src: "{{ playbook_dir }}/tasks/files/keys/kernel-mainline.pub"
    dest: "/tmp/"
    mode: 0600

- name: Add Mainline key
  become: true
  apt_key:
    # use locally save key to avoid possible temporary failures
    # repo: ppa:cappelikan/ppa
    file: "/tmp/kernel-mainline.pub"
    state: present

- name: Add Mainline apt repository
  become: true
  apt_repository:
    repo: "deb http://ppa.launchpad.net/cappelikan/ppa/ubuntu/ {{ ansible_distribution_release }} main"
    filename: "cappelikan-ubuntu-ppa-{{ ansible_distribution_release }}"
    state: present

- name: Install Mainline
  become: true
  apt:
    update_cache: yes
    state: present
    pkg:
    - mainline
  register: aptout

- debug: msg="{{ aptout.stdout_lines }}"
  when: aptout.stdout_lines is defined
