---
- name: Install dirmngr # required by gpg
  become: true
  apt:
    state: present
    pkg: dirmngr

- name: Add Kubuntu Backports apt repository
  become: true
  apt_repository:
    repo: ppa:kubuntu-ppa/backports
    state: present
    codename: "{{ ansible_distribution_release }}"
    update_cache: yes
  # The codename seems to be required to avoid errors of the shape:
  # The repository 'http://ppa.launchpad.net/kubuntu-ppa/backports/ubuntu sid Release' does not have a Release file.
