---
- name: Install dirmngr # required by gpg
  become: true
  apt:
    state: present
    pkg: dirmngr

- name: Add Kubuntu Backports apt repository
  become: true
  apt_repository:
    repo: ppa:kubuntu-ppa/backports
    state: present
    update_cache: yes
