---
- name: Install Zathura PDF reader
  become: true
  apt:
    state: present
    pkg:
    - zathura-pdf-poppler

- name: Install Latex Packages
  become: true
  apt:
    state: present
    pkg:
    - texlive
    - texlive-plain-generic
    - texlive-latex-extra
    - texlive-science
    - texlive-fonts-extra
    - texlive-lang-italian
    - texlive-xetex
    - texlive-bibtex-extra
    - cm-super
    - latexmk # for latexmk (used by vimtex)