---
- name: Install Main Packages
  become: true
  apt:
    state: present
    pkg:
    - vim
    - curl
    - wget
    - curl
    - gkrellm
    - net-tools
    - apt-transport-https
    - synaptic
    - unison-gtk
    - libfuse2 # required by AppImages, not installed by default in Ubuntu 22.04
