- name: Install Main Packages
  become: yes
  apt:
    state: latest
    pkg:
    - vim
    - curl
    - wget
    - curl
    - gkrellm
    - net-tools
    - apt-transport-https
    - synaptic
    - unison-gtk
    - thunderbird
  register: aptout

- debug: msg="{{ aptout.stdout_lines }}"
  when: aptout.stdout_lines is defined
