---
- name: Check whether snap is installed and on system path 
  ansible.builtin.command: 'which snap' 
  register: snap_installed
  ignore_errors: yes
  changed_when: false

- name: Remove Firefox and Thunderbird Snaps
  become: true
  ansible.builtin.snap:
    state: absent
    name:
    - firefox
    - thunderbird
  when: snap_installed.rc == 0

- name: Add Mozilla APT repository
  ansible.builtin.deb822_repository:
    name: mozillateamppa
    types: [deb]
    uris:
      - "https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu"
    suites: ["{{ ansible_distribution_release }}"]
    components: [main]
    state: present
    enabled: yes
    signed_by: "{{ lookup('ansible.builtin.file', 'mozilla.pub') }}"

- name: Check whether it is the first time we add Mozilla PPA
  stat:
    path: "/etc/apt/preferences.d/mozillateamppa"
  register: mozillateamppa_result

- name: Remove existing transitional packages the first time
  become: true
  ansible.builtin.apt:
    state: absent
    pkg:
    - firefox
    - thunderbird
  when: not mozillateamppa_result.stat.exists

- name: Copy Mozilla apt preference
  become: true
  ansible.builtin.copy:
    src: "files/mozillateamppa.txt"
    dest: "/etc/apt/preferences.d/mozillateamppa"
    mode: 0644

- name: Install Firefox and Thunderbird from APT
  become: true
  ansible.builtin.apt:
    update_cache: true
    state: present
    pkg:
    - firefox
    - thunderbird

- name: Copy Mozilla Unattended update preference
  become: true
  copy:
    src: "files/51unattended-upgrades-mozilla.txt"
    dest: "/etc/apt/apt.conf.d/51unattended-upgrades-mozilla"
    mode: 0644