---
- name: Install Other Packages
  become: true
  apt:
    state: present
    pkg:
    - emacs
    - homebank
    - ofx
    - vlc
    - meld
    - iotop
    - nethogs
    - p7zip-full
    - unrar
    - libreoffice-l10n-it
    - hyphen-it
    - hunspell-it
    - ispell
    - gimp
    - ppa-purge
    - tree
    - duf
#    - exfat-utils # Not available in Jammy?
