---
- name: Install Other Packages
  become: true
  apt:
    state: present
    pkg:
    - emacs
    - homebank
    - ofx
    - vlc
    - meld
    - iotop
    - nethogs
    - p7zip-full
    - unrar
    - libreoffice
    - libreoffice-l10n-it
    - hyphen-it
    - hunspell-it
    - ispell
    - gimp
    - ppa-purge
    - tree
#    - exfat-utils # Not available in Jammy?

- name: Install other recent packages
  become: true
  apt:
    state: present
    pkg:
    - duf
  when: ansible_distribution_version is version('22.04', '>=')

- name: Install chezmoi_modify_manager x86_64
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/VorpalBlade/chezmoi_modify_manager/releases/download/v3.2.0/chezmoi_modify_manager-v3.2.0-x86_64-unknown-linux-gnu.tar.gz"
    dest: /usr/local/bin
    remote_src: true
