---
- name: Copy Recoll apt key
  # The apt_key file is expected to be found on the remote host
  # so we first need to copy it
  become: true
  copy:
    src: "{{ playbook_dir }}/tasks/files/keys/recoll_signing_key.pub"
    dest: "/tmp/"
    mode: 0600

- name: Add Recoll key
  become: true
  apt_key:
    # use locally save key to avoid possible temporary failures
    # repo: ppa:recoll-backports/recoll-1.15-on
    file: "/tmp/recoll_signing_key.pub"
    state: present

- name: Add Recoll apt repository
  become: true
  apt_repository:
    repo: "deb http://ppa.launchpad.net/recoll-backports/recoll-1.15-on/ubuntu {{ ansible_distribution_release }} main"
    filename: "recoll-backports-ubuntu-recoll-1_15-on-{{ ansible_distribution_release }}"
    state: present

- name: Install Recoll
  become: true
  apt:
    update_cache: yes
    state: present
    pkg:
    - recoll
    - unrtf
    - untex
    - djvulibre-bin
  register: aptout

- debug: msg="{{ aptout.stdout_lines }}"
  when: aptout.stdout_lines is defined

- name: Create Recoll configuration directory
  file:
    path: '~/.recoll'
    state: directory
    mode: 0775

- name: Set Recoll configuration
  copy:
    src: "{{ playbook_dir }}/tasks/files/recoll/"
    dest: "~/.recoll/"
    mode: 0600
