- name: Copy Recoll apt key
  # The apt_key file is expected to be found on the remote host
  # so we first need to copy it
  become: yes
  copy:
    src: "{{ playbook_dir }}/tasks/files/keys/recoll_signing_key.pub"
    dest: "/tmp/"

- name: Add Recoll key
  become: yes
  apt_key:
    # use locally save key to avoid possible temporary failures
    # repo: ppa:recoll-backports/recoll-1.15-on
    file: "/tmp/recoll_signing_key.pub"
    state: present

- name: Install Recoll
  become: yes
  apt:
    update_cache: yes
    state: latest
    pkg:
    - recoll
    - unrtf
    - untex
    - djvulibre-bin
  register: aptout

- debug: msg="{{ aptout.stdout_lines }}"
  when: aptout.stdout_lines is defined

- name: Create Recoll configuration directory
  file:
    path: '~/.recoll'
    state: directory

- name: Set Recoll configuration
  copy:
    src: "{{ playbook_dir }}/tasks/files/recoll/"
    dest: "~/.recoll/"
