---
- name: Add Recoll APT repository
  become: true
  ansible.builtin.deb822_repository:
    name: recoll
    types: [deb]
    uris:
      - "https://ppa.launchpadcontent.net/recoll-backports/recoll-1.15-on/ubuntu"
    suites: ["{{ ansible_distribution_release }}"]
    components: [main]
    state: present
    enabled: yes
    signed_by: "{{ lookup('ansible.builtin.file', 'recoll_signing_key.pub') }}"
# the signing key can be downloaded from https://launchpad.net/~recoll-backports/+archive/ubuntu/recoll-1.15-on
# in particular following the link in "Signing key" 

- name: Install Recoll
  become: true
  ansible.builtin.apt:
    update_cache: yes
    state: present
    pkg:
    - recoll
    - unrtf
    - untex
    - djvulibre-bin