---
- name: Install Ubuntu restricted extras
  become: true
  apt:
    state: present
    pkg:
    - ubuntu-restricted-extras
  register: aptout

- debug: msg="{{ aptout.stdout_lines }}"
  when: aptout.stdout_lines is defined
