---
# These depend on a specific version of Ubuntu

- name: Remove mlocate
  become: true
  apt:
    state: absent
    pkg:
    - mlocate
  when: ansible_distribution_version is version('21.04', '>=')

- name: Install plocate
  become: true
  apt:
    state: present
    pkg:
    - plocate
  when: ansible_distribution_version is version('21.04', '>=')
