---
- name: Install Antigen requirements
  become: true
  apt:
    state: present
    pkg:
    - fonts-powerline
    - curl
    - git
  register: aptout

- debug: msg="{{ aptout.stdout_lines }}"
  when: aptout.stdout_lines is defined

- name: Download Antigen
  get_url:
    url: "https://git.io/antigen"
    dest: "~/antigen.zsh"

- name: Set Antigen configuration
  copy:
    src: "{{ playbook_dir }}/tasks/files/antigen/"
    dest: "~/"
