---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: kubuntu-instance
    image: kubuntu-ansible
    dockerfile: ../default/Dockerfile
    build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: ../default/verify.yml
