---
# Does not work in Ansible/Molecule/Docker
- name: Start snapd.service
  become: true
  ansible.builtin.systemd_service:
    name: snapd
    state: started

- name: Install Skype (snap package)
  become: true
  community.general.snap:
    name:
      - skype
