---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: ubuntu-instance
    image: custom-${MOLECULE_DOCKER_DISTRO:-ubuntu-default}-ansible
    dockerfile: ../docker/${MOLECULE_DOCKER_DISTRO:-ubuntu-default}/Dockerfile
    command: ""
    privileged: true
    build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ../${MOLECULE_DISTRO:-ubuntu}/converge.yml
verifier:
  name: ansible
