---
# On PR we also test with older versions of the
# Docker images
name: Molecule PR
on:
  pull_request:
    paths-ignore:
     - '**.md'

env:
  PYTHON_VERSION: '3.10.x'

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - ubuntu-22.04

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install test dependencies.
        run: |
          pip install -r pip/requirements.txt
  
      - name: Show versions.
        run: |
          molecule --version
          yamllint --version
          ansible-lint --version

      - name: Run Molecule tests.
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
